# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

####################################################################
# First steps                                                      #
####################################################################
- name: "Installing some App acceptance environment specific additions"
  debug: msg="Installing some App acceptance environment specific additions"
#  when: <some condition>
  notify:                                                                                         
    - someApp_smoke

####################################################################
# And then something else                                          #
####################################################################

####################################################################
# Kick off handlers                                                #
####################################################################
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers